% ==========================================================================
%  WAVE PARAMETER STATISTICS + BREAKUP ANALYSIS + WAVELENGTH RATIO ANALYSIS
%  Reads waves_class.csv (output of wave_classifier.m) and produces:
%
%  (1) STATISTICS TABLE
%      Prints min / max / mean / median of all key dimensionless parameters
%      (k, lambda, H/lambda, a/lambda, kH, kh, kLd, h/lambda, I_breakup),
%      split into ice and water subsets, with full context columns
%      (lambda, T_set, f_set, T_s, a, ka_set) for each statistic.
%      Rows with nearly zero amplitude (a_m ≈ 0) are removed before any computation.
%
%  (2) FOUR BREAKUP PLOTS
%      Shows the normalised breakup parameter I/I_br (Voermans et al. 2020,
%      threshold I_br = 0.014) with propagated uncertainty error bars:
%
%        Plot 1 — I/I_br vs ka_set  at a single fixed T_set  (user-set)
%        Plot 2 — I/I_br vs T_set   at a single fixed ka_set (user-set)
%        Plot 3 — I/I_br vs ka_set  sweeping all T_set  (colour-coded)
%        Plot 4 — I/I_br vs T_set   sweeping all ka_set (colour-coded)
%
%      Error bars are read from dI_breakup in the CSV
%
%  (3) TWO WAVELENGTH-RATIO PLOTS  (ice-modified vs. open-water wavelength)
%      Uses lambda_ratio_ice_over_setwater = lambda_m(ice) / lambda_open_water_set_m,
%      and its uncertainty d_lambda_ratio_ice_over_setwater, both read directly
%      from the CSV (computed once in wave_classifier.m — see that
%      script's header for exactly how each wavelength and the uncertainty
%      are derived;):
%
%        Plot 5 — lambda_ratio vs f_set   1 curve per set steepness (ka_set)
%        Plot 6 — lambda_ratio vs ka_set  1 curve per set frequency (f_set,
%                                          grouped via the corresponding T_set)
%
%      If waves_class.csv was generated by an older wave_classifier.m that
%      doesn't export these columns yet, a warning is printed and Plots 5-6
%      are skipped (re-run the updated wave_classifier.m to regenerate it).
%
%  USAGE
%      1. Run wave_classifier.m first to generate waves_class.csv.
%      2. Set csv_path, fixed_T_set, fixed_ka_set, save_path below.
%      3. Run this script.
%
%  BACKWARD COMPATIBILITY
%      If waves_class.csv was generated by wave_classifier v1 (missing
%      T_set or dI_breakup columns), a warning is printed and the script
%      falls back: T_set <- T_s (fixed-T filter approximate),
%      error bars suppressed. Same idea for the wavelength-ratio columns
%      (Section 3) — see above.
%
%  REFERENCES
%      Voermans et al. (2020). The Cryosphere, 14, 4265-4278.
% ==========================================================================
clear; clc; close all;

%% =========================================================================
% USER PARAMETERS
% =========================================================================

csv_path = 'waves_class.csv';

% ---- Breakup threshold ----
I_br_threshold = 0.014;   % Voermans et al.

% ---- Plot settings ----

tol_ka       = 0.005;     % Matching tolerance on ka_set
tol_T        = 0.01;      % Matching tolerance on T_set [s]

% ---- Export settings ----
save_fig   = true;
save_path  = 'E:\SIWWI2026\wave_classifier\';

% =========================================================================
% LOAD DATA
% =========================================================================

if ~isfile(csv_path)
    error('CSV file not found: %s', csv_path);
end

T = readtable(csv_path);

% ------------------------------------------------------------------
%  Backward-compatibility: if T_set column is absent (old CSV from
%  wave_classifier_v1), fall back to T_s so the script still runs,
%  but print a warning so the user knows to regenerate the CSV.
% ------------------------------------------------------------------
if ~ismember('T_set', T.Properties.VariableNames)
    warning(['Column T_set not found in CSV. ' ...
             'Re-run wave_classifier_v2 to regenerate waves_class.csv. ' ...
             'Falling back to T_s for now (fixed-T filter will be approximate).']);
    T.T_set = T.T_s;
end
% Backward-compatibility: dI_breakup absent in CSVs generated before this fix
if ~ismember('dI_breakup', T.Properties.VariableNames)
    warning('Column dI_breakup not found. Re-run wave_classifier_v2. Error bars will be suppressed.');
    T.dI_breakup = NaN(height(T), 1);
end

% Backward-compatibility: wavelength-ratio columns (Section 3 / Plots 5-6)
% absent in CSVs generated before this fix.
has_lambda_ratio_cols = all(ismember( ...
    {'f_set_Hz','lambda_open_water_set_m', ...
     'lambda_ratio_ice_over_setwater','d_lambda_ratio_ice_over_setwater'}, ...
    T.Properties.VariableNames));
if ~has_lambda_ratio_cols
    warning(['Wavelength-ratio columns not found in CSV. ' ...
             'Re-run the updated wave_classifier.m to regenerate waves_class.csv. ' ...
             'Plots 5-6 will be skipped.']);
end

% =========================================================================
% Remove artefact rows (a_m ≈ 0)
% =========================================================================

N_before = height(T);
T = T(T.a_m > 1e-10, :);
N_after  = height(T);

fprintf('Loaded %d rows  ->  %d artefact row(s) removed  ->  %d rows retained.\n\n', ...
    N_before, N_before - N_after, N_after);

% =========================================================================
% Subsets
% =========================================================================

T_ice   = T(T.Has_Ice == 1, :);
T_water = T(T.Has_Ice == 0, :);

fprintf('ICE rows  : %d\n', height(T_ice));
fprintf('WATER rows: %d\n\n', height(T_water));

% =========================================================================
% STATISTICS 
% =========================================================================
%
%  Each COLS entry: {column_name, display_label, ice_only_flag}
% =========================================================================

COLS = {
    'k_rad_m',             'k  [rad/m]',                           false;
    'lambda_m',            'lambda  [m]',                          false;
    'H_over_lambda',       'H/lambda  (water depth / lambda)',     false;
    'H_over_lambda_water', 'H/lambda_water  (= H/lambda, alias)',  false;
    'a_over_lambda',       'a/lambda',                             false;
    'kH',                  'kH',                                   false;
    'kh',                  'kh  (ice thickness * k)',              true;
    'kLd',                 'kLd  (k * elastic length)',            true;
    'h_over_lambda',       'h/lambda  (ice thickness / lambda)',   true;
    'I_breakup',           'I_breakup',                            true;
};

for s = 1:size(COLS,1)

    col      = COLS{s,1};
    display  = COLS{s,2};
    ice_only = COLS{s,3};

    fprintf('%s\n', repmat('=',1,90));
    fprintf('  %s\n', display);
    fprintf('%s\n', repmat('=',1,90));

    if ice_only
        fprintf('  >> ICE only <<\n');
        report_col(col, T_ice);
    else
        fprintf('  [ ICE ]\n');
        report_col(col, T_ice);
        fprintf('  [ WATER ]\n');
        report_col(col, T_water);
    end
end

fprintf('%s\n', repmat('=',1,90));
fprintf('Done with statistics.\n\n');

%% =========================================================================
% BREAKUP PLOTTING SECTION
% =========================================================================
df = T;
filename_3 = 'I_vs_ka_fixed_T';
filename_4 = 'I_vs_T_fixed_ka';


% Keep only ice cases
if ismember('Has_Ice', df.Properties.VariableNames)
    df = df(df.Has_Ice == 1, :);
else
    warning('Has_Ice column not found. Assuming all rows are ice cases.');
end
% Remove rows with NaN in the plotting variables
df = df(~isnan(df.I_breakup) & ~isnan(df.ka_set) & ~isnan(df.T_set), :);

% Compute normalised breakup ratio
df.I_ratio = df.I_breakup / I_br_threshold;

% Create save directory if needed
if save_fig && ~exist(save_path, 'dir')
    mkdir(save_path);
end

% Print available (T_set, ka_set) combinations 

fprintf('Available (T_set, ka_set) combinations in ice data:\n');
combos = unique(df(:, {'T_set','ka_set'}), 'rows');
disp(combos);

% =========================================================================
% LOWEST I/I_br POINT ANALYSIS -- (safety check because I had suspicious points, but
% ok no negative points  in the end)
% =========================================================================
fprintf('\n--- Lowest I/I_br Point Analysis ---\n');

%  absolute minimum y-value (I/I_br ratio) 
min_I_ratio = min(df.I_ratio);

% row indices that contain this minimum value
idx_min = find(df.I_ratio == min_I_ratio);

%  mean x and y values for these points
mean_ka_set  = mean(df.ka_set(idx_min));
mean_T_set   = mean(df.T_set(idx_min));
mean_I_ratio = mean(df.I_ratio(idx_min)); 


fprintf('Lowest I/I_br ratio found: %.4f\n', mean_I_ratio);
fprintf('Number of data points at this minimum: %d\n', length(idx_min));
fprintf('Mean coordinates for Plot 1 (x = ka_set, y = I/I_br): (%.4f, %.4f)\n', mean_ka_set, mean_I_ratio);
fprintf('Mean coordinates for Plot 2 (x = T_set,  y = I/I_br): (%.4f, %.4f)\n', mean_T_set, mean_I_ratio);
fprintf('--------------------------------------\n\n');

%% =========================================================================
% PLOT 1 : I/I_br vs ka_set  (fixed T_set)
%   Filter on T_set (nominal set period), not T_s (measured).
% =========================================================================
fixed_T_set  = 0.6;       % Fixed set period [s] for Plot 1


% use T_set column, not T_s
idx_fixed_T = abs(df.T_set - fixed_T_set) <= tol_T;
df_plot1    = df(idx_fixed_T, :);

fig1 = figure('Name','I/I_br vs Steepness', 'Color','w', 'Position',[100 100 700 500]);
hold on; grid on;

if ~isempty(df_plot1)

    df_plot1 = sortrows(df_plot1, 'ka_set');

    % Normalise uncertainty
    dI_ratio_1 = df_plot1.dI_breakup / I_br_threshold;

    eb1 = errorbar(df_plot1.ka_set, df_plot1.I_ratio, dI_ratio_1, ...
        'x', 'LineWidth', 1.5, 'MarkerSize', 14, ...
        'MarkerFaceColor', 'b', 'Color', 'b', ...
        'CapSize', 6);

    yline(1, 'r--', 'Breakup thresh.  ', ...
          'LineWidth',1.5, 'LabelHorizontalAlignment','left');
    ylim([-0.05, inf]);

    xlabel('  $(ka)_\mathrm{set}$', 'Interpreter','latex', 'FontSize',18);
    ylabel('$I / I_\mathrm{br}$',              'Interpreter','latex', 'FontSize',18);
    title(sprintf('T_{set} = %.2f s', fixed_T_set), 'FontSize',14);

    fprintf('\nPlot 1 — %d points for T_set ≈ %.2f s:\n', height(df_plot1), fixed_T_set);
    fprintf('  ka_set values: ');
    fprintf('%.4f  ', df_plot1.ka_set);
    fprintf('\n');

else
    title(sprintf('No data found for T_{set} \\approx %.2f s', fixed_T_set));
    fprintf('\nPlot 1 — WARNING: no ice rows found for T_set ≈ %.2f s (tol = %.3f s).\n', ...
        fixed_T_set, tol_T);
    fprintf('  Available T_set values: ');
    fprintf('%.4f  ', unique(df.T_set));
    fprintf('\n');
end

% =========================================================================
% Export plot 1
% =========================================================================
if save_fig
    %  Dynamically create the filename strings
    filename_1 = sprintf('I_vs_ka_fixed_T_%.2fs', fixed_T_set);

    
    %  Replace decimals '.' with 'p' 
    %    e.g., "1.00s" becomes "1p00s" to prevent file extension errors
    filename_1 = strrep(filename_1, '.', 'p');

    %  Export Plot 1
    exportgraphics(fig1, fullfile(save_path, [filename_1 '.png']), 'Resolution',300);
    exportgraphics(fig1, fullfile(save_path, [filename_1 '.pdf']), 'ContentType','vector');
    

    
    % Print confirmation to the console
    fprintf('\nPlots saved to: %s\n', save_path);
    fprintf('  - %s.png / .pdf\n', filename_1);
end


%% =========================================================================
% PLOT 2 : I/I_br vs T_set  (fixed ka_set)
%   Filter on ka_set; x-axis is the nominal set period T_set.
% =========================================================================
fixed_ka_set = 0.1;      % Fixed steepness for Plot 2

% filter by ka_set, plot against T_set
idx_fixed_ka = abs(df.ka_set - fixed_ka_set) <= tol_ka;
df_plot2     = df(idx_fixed_ka, :);

fig2 = figure('Name','I/I_br vs Period', 'Color','w', 'Position',[150 150 700 500]);
hold on; grid on;

if ~isempty(df_plot2)

    df_plot2 = sortrows(df_plot2, 'T_set');

    dI_ratio_2 = df_plot2.dI_breakup / I_br_threshold;

    eb2 = errorbar(df_plot2.T_set, df_plot2.I_ratio, dI_ratio_2, ...
        'x', 'LineWidth', 1.5, 'MarkerSize', 14, ...
        'MarkerFaceColor', 'b', 'Color', 'b', ...
        'CapSize', 6);

    yline(1, 'r--', 'Breakup thresh.  ', ...
          'LineWidth',1.5, 'LabelHorizontalAlignment','left');
    ylim([-0.05, inf]);

  
    title(sprintf('(ak)_{set} = %.2f ', fixed_ka_set), 'FontSize',14);
    xlabel(' $T_\mathrm{set}$  [s]', 'Interpreter','latex', 'FontSize',18);
    ylabel('$I / I_\mathrm{br}$',               'Interpreter','latex', 'FontSize',18);


    fprintf('\nPlot 2 — %d points for ka_set ≈ %.3f (tol = %.3f):\n', ...
        height(df_plot2), fixed_ka_set, tol_ka);
    fprintf('  T_set values: ');
    fprintf('%.4f  ', df_plot2.T_set);
    fprintf('\n');

else
    title(sprintf('No data found for ka_{set} \\approx %.3f', fixed_ka_set));
    fprintf('\nPlot 2 — WARNING: no ice rows found for ka_set ≈ %.3f (tol = %.3f).\n', ...
        fixed_ka_set, tol_ka);
    fprintf('  Available ka_set values: ');
    fprintf('%.4f  ', unique(df.ka_set));
    fprintf('\n');
end

% =========================================================================
% Export plot 2
% =========================================================================
if save_fig

    filename_2 = sprintf('I_vs_T_fixed_ka_%.3f', fixed_ka_set);
    

    filename_2 = strrep(filename_2, '.', 'p');

    
    %  Export Plot 2
    exportgraphics(fig2, fullfile(save_path, [filename_2 '.png']), 'Resolution',300);
    exportgraphics(fig2, fullfile(save_path, [filename_2 '.pdf']), 'ContentType','vector');
    
    % Print confirmation to the console
    fprintf('\nPlots saved to: %s\n', save_path);
    fprintf('  - %s.png / .pdf\n', filename_2);
end

%% =========================================================================
% PLOT 3 : I/I_br vs ka_set  (Iterating over all T_set)
% =========================================================================
fig3 = figure('Name','I/I_br vs Steepness', 'Color','w', 'Position',[100 100 700 500]);
hold on; grid on;

% Get all unique T_set values
unique_T_set = unique(df.T_set);
colors1 = lines(length(unique_T_set)); 

fprintf('\nPlot 1 — Plotting curves for %d unique T_set values...\n', length(unique_T_set));

for i = 1:length(unique_T_set)
    current_T = unique_T_set(i);
    idx_T = abs(df.T_set - current_T) <= tol_T;
    df_plot1 = df(idx_T, :);
    
    if ~isempty(df_plot1)
        df_plot1 = sortrows(df_plot1, 'ka_set');
        % Normalise uncertainty
        dI_ratio_1 = df_plot1.dI_breakup / I_br_threshold;
        
        errorbar(df_plot1.ka_set, df_plot1.I_ratio, dI_ratio_1, ...
            'x', 'LineWidth', 1.5, 'MarkerSize', 14, ...
            'MarkerFaceColor', colors1(i,:), 'Color', colors1(i,:), ...
            'CapSize', 6, 'DisplayName', sprintf('T_{set} = %.2f s', current_T));
    end
end

yline(1, 'r--','LineWidth',1.5, 'DisplayName', 'Breakup thresh.');
xlabel('  $(ka)_\mathrm{set}$', 'Interpreter','latex', 'FontSize',18);
ylabel('$I / I_\mathrm{br}$',              'Interpreter','latex', 'FontSize',18);
legend('Location', 'best');

%% =========================================================================
% PLOT 4 : I/I_br vs T_set  (Iterating over all ka_set)
% =========================================================================
fig4 = figure('Name','I/I_br vs Period', 'Color','w', 'Position',[150 150 700 500]);
hold on; grid on;

% Get all unique ka_set values
unique_ka_set = unique(df.ka_set);
colors2 = lines(length(unique_ka_set)); % Generate distinct colors

fprintf('\nPlot 2 — Plotting curves for %d unique ka_set values...\n', length(unique_ka_set));

for i = 1:length(unique_ka_set)
    current_ka = unique_ka_set(i);
    idx_ka = abs(df.ka_set - current_ka) <= tol_ka;
    df_plot2 = df(idx_ka, :);
    
    if ~isempty(df_plot2)
        df_plot2 = sortrows(df_plot2, 'T_set');
        dI_ratio_2 = df_plot2.dI_breakup / I_br_threshold;
        
        errorbar(df_plot2.T_set, df_plot2.I_ratio, dI_ratio_2, ...
            'x', 'LineWidth', 2, 'MarkerSize', 14, ...
            'MarkerFaceColor', colors2(i,:), 'Color', colors2(i,:), ...
            'CapSize', 6, 'DisplayName', sprintf('(ka)_{set} = %.3f', current_ka));
    end
end

yline(1, 'r--', 'LineWidth',1.5, 'DisplayName', 'Breakup thresh.');
xlabel('  $T_\mathrm{set}$  [s]', 'Interpreter','latex', 'FontSize',18);
ylabel('$I / I_\mathrm{br}$',               'Interpreter','latex', 'FontSize',18);
legend('Location', 'best', 'NumColumns', 2);


%% =========================================================================
% Export plots 3 and 4
% =========================================================================

if save_fig

    exportgraphics(fig3, fullfile(save_path, [filename_3 '.png']), 'Resolution',300);
    exportgraphics(fig3, fullfile(save_path, [filename_3 '.pdf']), 'ContentType','vector');
    exportgraphics(fig4, fullfile(save_path, [filename_4 '.png']), 'Resolution',300);
    exportgraphics(fig4, fullfile(save_path, [filename_4 '.pdf']), 'ContentType','vector');

    fprintf('\nPlots saved to: %s\n', save_path);
end

%% =========================================================================
% WAVELENGTH-RATIO PLOTTING SECTION 
% =========================================================================

if has_lambda_ratio_cols

df_ratio = T(T.Has_Ice == 1 & ~isnan(T.lambda_ratio_ice_over_setwater) ...
             & ~isnan(T.ka_set) & ~isnan(T.T_set), :);

if isempty(df_ratio)
    warning('No valid ice rows with wavelength-ratio data found. Skipping Plots 5-6.');
else

%% =========================================================================
% PLOT 5 : lambda_ratio vs f_set   (1 curve per set steepness ka_set)
% =========================================================================
fig5 = figure('Name','Wavelength ratio vs Frequency', 'Color','w', 'Position',[100 100 700 500]);
hold on; grid on;
set(gca, 'FontSize', 16);
axis square;

unique_ka_ratio = unique(df_ratio.ka_set);
colors5 = lines(length(unique_ka_ratio));

fprintf('Plot 5 — Plotting curves for %d unique ka_set values...\n', length(unique_ka_ratio));

for i = 1:length(unique_ka_ratio)
    current_ka = unique_ka_ratio(i);
    idx_ka = abs(df_ratio.ka_set - current_ka) <= tol_ka;
    sub = df_ratio(idx_ka, :);

    if ~isempty(sub)
        sub = sortrows(sub, 'f_set_Hz');

        errorbar(sub.f_set_Hz, sub.lambda_ratio_ice_over_setwater, ...
            sub.d_lambda_ratio_ice_over_setwater, ...
            'x', 'LineWidth', 1.5, 'MarkerSize', 14, ...
            'MarkerFaceColor', colors5(i,:), 'Color', colors5(i,:), ...
            'CapSize', 6, 'DisplayName', sprintf('(ka)_{set} = %.3f', current_ka));
    end
end

xlabel('$f_\mathrm{set}$  [Hz]', 'Interpreter','latex', 'FontSize',18);
ylabel('$\lambda_\mathrm{m} / \lambda_\mathrm{set}$', 'Interpreter','latex', 'FontSize',18);
legend('Location', 'best', 'NumColumns', 2, 'FontSize', 12);

filename_5 = 'lambda_ratio_vs_fset_by_ka';

if save_fig
    exportgraphics(fig5, fullfile(save_path, [filename_5 '.png']), 'Resolution',300);
    exportgraphics(fig5, fullfile(save_path, [filename_5 '.pdf']), 'ContentType','vector');
    fprintf('\nPlots saved to: %s\n', save_path);
    fprintf('  - %s.png / .pdf\n', filename_5);
end

%% =========================================================================
% PLOT 6 : lambda_ratio vs ka_set  (1 curve per set frequency f_set)
%   Curves are grouped by T_set (matches the tol_T grouping used elsewhere
%   in this script), and labelled by the corresponding f_set = 1/T_set.
% =========================================================================
fig6 = figure('Name','Wavelength ratio vs Steepness', 'Color','w', 'Position',[150 150 700 500]);
hold on; grid on;
set(gca, 'FontSize', 16);
axis square;

unique_Tset_ratio = unique(df_ratio.T_set);
colors6 = lines(length(unique_Tset_ratio));

fprintf('\nPlot 6 — Plotting curves for %d unique T_set (f_set) values...\n', length(unique_Tset_ratio));

for i = 1:length(unique_Tset_ratio)
    current_T = unique_Tset_ratio(i);
    idx_T = abs(df_ratio.T_set - current_T) <= tol_T;
    sub = df_ratio(idx_T, :);

    if ~isempty(sub)
        sub = sortrows(sub, 'ka_set');
        current_f = 1 / current_T;

        errorbar(sub.ka_set, sub.lambda_ratio_ice_over_setwater, ...
            sub.d_lambda_ratio_ice_over_setwater, ...
            'x', 'LineWidth', 1.5, 'MarkerSize', 14, ...
            'MarkerFaceColor', colors6(i,:), 'Color', colors6(i,:), ...
            'CapSize', 6, 'DisplayName', sprintf('f_{set} = %.3f Hz', current_f));
    end
end
xlim([0.015 0.109])
xlabel('  $(ka)_\mathrm{set}$', 'Interpreter','latex', 'FontSize',18);
ylabel('$\lambda_\mathrm{m} / \lambda_\mathrm{set}$', 'Interpreter','latex', 'FontSize',18);
legend('Location', 'eastoutside', 'NumColumns', 1, 'FontSize', 12);

filename_6 = 'lambda_ratio_vs_ka_by_fset';

if save_fig
    exportgraphics(fig6, fullfile(save_path, [filename_6 '.png']), 'Resolution',300);
    exportgraphics(fig6, fullfile(save_path, [filename_6 '.pdf']), 'ContentType','vector');
    fprintf('\nPlots saved to: %s\n', save_path);
    fprintf('  - %s.png / .pdf\n', filename_6);
end

end % if ~isempty(df_ratio)
end % if has_lambda_ratio_cols

%% =========================================================================
% LOCAL FUNCTIONS
% =========================================================================

function report_col(col, subset)

    vals  = subset.(col);
    valid = ~isnan(vals);

    if ~any(valid)
        fprintf('  [no data]\n\n');
        return
    end

    vals_valid = vals(valid);
    sub_valid  = subset(valid, :);

    stat_names = {'min','max','mean','median'};
    stat_vals  = [min(vals_valid), max(vals_valid), ...
                  mean(vals_valid), median(vals_valid)];

    for s = 1:4

        stat = stat_names{s};
        val  = stat_vals(s);

        if s <= 2
            if s == 1, [~,idx] = min(vals_valid);
            else,      [~,idx] = max(vals_valid); end
            row = sub_valid(idx, :);
            ctx = context_str(row, col, false);
        else
            [~,idx] = min(abs(sub_valid.(col) - val));
            row = sub_valid(idx, :);
            ctx = context_str(row, col, true);
        end

        fprintf('    %-7s %14.6g     %s\n', stat, val, ctx);
    end

    fprintf('\n');
end


function str = context_str(row, col, is_nearest)

    parts = {};

    if ~strcmp(col,'lambda_m')
        parts{end+1} = sprintf('lambda=%.4f m', row.lambda_m);
    end

    % Report both set period and measured period for clarity
    T_set_val = row.T_set;
    T_s_val   = row.T_s;
    f_set_val = 1 / T_set_val;

    parts{end+1} = sprintf('T_set=%.4f s  f_set=%.4f Hz', T_set_val, f_set_val);
    parts{end+1} = sprintf('T_s=%.4f s', T_s_val);
    parts{end+1} = sprintf('a=%.5g m', row.a_m);
    parts{end+1} = sprintf('ka_set=%.4f', row.ka_set);

    str = strjoin(parts, '  |  ');

    if is_nearest
        str = [str '  [nearest row]'];
    end
end